where_single_line= true
use_small_heuristics = "Max"
max_width = 120
struct_field_align_threshold = 40
single_line_if_else_max_width = 150
fn_call_width = 150
reorder_impl_items = true
normalize_comments = true
imports_granularity = "Crate"
indent_style = "Visual"
imports_indent = "Visual"
#fn_single_line = true
fn_args_layout = "Compressed"
enum_discrim_align_threshold = 40
chain_width = 150
attr_fn_like_width = 150
array_width = 150
